from fastapi import APIRouter, Depends, HTTPException, Request
from core.security import limiter
from sqlalchemy.ext.asyncio import AsyncSession
from models.enums import RecommendationMode
from schemas.tasks import TaskResponse, TaskUpdate, TaskCreate, TaskRecommendationResponse
from services.task_service import TaskService
from services.recommendation_service import RecommendationService as R
from ..deps import get_current_user, get_db

task_router = APIRouter(prefix="/tasks", tags=["tasks"])

# This endpoint is currently commented out because the creation of tasks is primarily intended to be done through the recommendation system. However, it can be easily re-enabled if we want to allow users to create custom tasks that are not generated by the recommendation engine.
# @task_router.post("/create/", response_model=TaskResponse)
# async def create_task(
#     task_schema: TaskCreate,
#     db: AsyncSession=Depends(get_db),
#     current_user = Depends(get_current_user)
# ):
#     """Endpoint to create a new task."""
#     try:
#         result = await TaskService.create_task(db, task_schema, current_user.id)
#         return result
#     except ValueError as e:
#         raise HTTPException(
#             status_code=400,
#             detail=str(e)
#         )
    

@task_router.post("/{goal_id}/recommend")
@limiter.limit("5/minute")
@limiter.limit("10/day")
async def create_recommendation_task(
    request: Request,
    goal_id: int,
    db: AsyncSession=Depends(get_db),
    current_user = Depends(get_current_user)
):
    """Endpoint to create a new task."""
    try:
        result = await R.generate_recommendation(db, goal_id, current_user.id)
        return result
    except ValueError as e:
        raise HTTPException(
            status_code=400,
            detail=str(e)
        )
    
@task_router.post("/{goal_id}/recommend/single/", response_model=TaskRecommendationResponse)
@limiter.limit("5/minute")
@limiter.limit("15/day")
async def recommend_task(
    request: Request,
    goal_id: int,
    db: AsyncSession=Depends(get_db),
    current_user = Depends(get_current_user)
):
    """Endpoint to recommend a task."""
    try:
        result = await R.recommend_task(db, goal_id, current_user.id)
        return result
    except ValueError as e:
        raise HTTPException(
            status_code=400,
            detail=str(e)
        )

@task_router.get("/{task_id}/alternative", response_model=TaskResponse)
async def get_alternative_task(
    task_id: int,
    mode: RecommendationMode,
    session: AsyncSession=Depends(get_db),
    current_user = Depends(get_current_user)
):
    """Endpoint to get an alternative task based on the specified mode."""
    try:
        result = await R.alternative_task(session, task_id, mode, current_user.id)
        return result
    except ValueError as e:
        raise HTTPException(
            status_code=400,
            detail=str(e)
        )
    

@task_router.get("/from-goal/{goal_id}", response_model=list[TaskResponse])
async def list_goal_tasks(
    goal_id: int,
    db: AsyncSession=Depends(get_db),
    current_user = Depends(get_current_user)
):
    """Endpoint to list all tasks of the current user."""
    try:
        result = await TaskService.list_goal_tasks(db,  goal_id, current_user.id)
        return result
    except HTTPException:
        raise
    except ValueError as e:
        raise HTTPException(
            status_code=400,
            detail=str(e)
        )


@task_router.get("/{task_id}", response_model=TaskResponse)
async def get_task_by_id(
    task_id: int,
    db: AsyncSession=Depends(get_db),
    current_user = Depends(get_current_user)
):
    """Endpoint to get a specific task by its ID."""
    try:
        result = await TaskService.get_task_by_id(db, task_id, current_user.id)
        return result
    except HTTPException:
        raise
    except ValueError as e:
        raise HTTPException(
            status_code=400,
            detail=str(e)
        )
    

@task_router.patch("/{task_id}")
@limiter.limit("5/minute")
async def update_task(
    request: Request,
    task_id: int,
    task_update_schema: TaskUpdate,
    session: AsyncSession=Depends(get_db),
    current_user = Depends(get_current_user)
):
    """Endpoint to update a task."""
    try:
        result = await TaskService.update_task(session, task_id, task_update_schema, current_user.id)
        return result
    except HTTPException:
        raise
    except ValueError as e:
        raise HTTPException(
            status_code=400,
            detail=str(e)
        )


@task_router.delete("/{task_id}")
@limiter.limit("5/minute")
async def delete_task(
    request: Request,
    task_id: int,
    session: AsyncSession=Depends(get_db),
    current_user = Depends(get_current_user)    
):
    """Endpoint to delete a task."""
    try:
        await TaskService.delete_task(session, task_id, current_user.id)
        return {"detail": "Task deleted successfully"}
    except HTTPException:
        raise
    except ValueError as e:
        raise HTTPException(
            status_code=400,
            detail=str(e)
        )
